// <auto-generated />
using System;
using CourseGuide.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CourseGuide.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240921064550_Database_v.1")]
    partial class Database_v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CourseGuide.Objects.Models.Entities.RestaurantModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idrestaurant");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailRestaurant")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("emailrestaurant");

                    b.Property<int>("IdOwner")
                        .HasColumnType("integer")
                        .HasColumnName("idowner");

                    b.Property<string>("NameRestaurant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("namerestaurant");

                    b.Property<string>("PhoneRestaurant")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phonerestaurant");

                    b.HasKey("Id");

                    b.HasIndex("IdOwner");

                    b.ToTable("restaurants");
                });

            modelBuilder.Entity("CourseGuide.Objects.Models.Entities.TableModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idtable");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CapacityTable")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("capacitytable");

                    b.Property<int>("IdRestaurant")
                        .HasColumnType("integer")
                        .HasColumnName("idrestaurant");

                    b.Property<string>("LocationTable")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locationtable");

                    b.Property<string>("NumberTable")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numbertable");

                    b.Property<int?>("RestaurantModelId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValueTable")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("valuetable");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantModelId");

                    b.ToTable("tables");
                });

            modelBuilder.Entity("CourseGuide.Objects.Models.Entities.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iduser");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailUser")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("emailuser");

                    b.Property<string>("ImageProfile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imageprofile");

                    b.Property<string>("NameUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nameuser");

                    b.Property<string>("PasswordUser")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("passworduser");

                    b.Property<string>("PhoneUser")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phoneuser");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailUser = "master@development.com",
                            ImageProfile = "",
                            NameUser = "Master",
                            PasswordUser = "99db87c3278f5eaa517260eaaa2b4b376be63d7f8a79c0f43992a493a3de8fc9",
                            PhoneUser = ""
                        });
                });

            modelBuilder.Entity("CourseGuide.Objects.Models.Entities.RestaurantModel", b =>
                {
                    b.HasOne("CourseGuide.Objects.Models.Entities.UserModel", "OwnerModel")
                        .WithMany("RestaurantsModel")
                        .HasForeignKey("IdOwner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerModel");
                });

            modelBuilder.Entity("CourseGuide.Objects.Models.Entities.TableModel", b =>
                {
                    b.HasOne("CourseGuide.Objects.Models.Entities.RestaurantModel", "RestaurantModel")
                        .WithMany("TablesModel")
                        .HasForeignKey("RestaurantModelId");

                    b.Navigation("RestaurantModel");
                });

            modelBuilder.Entity("CourseGuide.Objects.Models.Entities.RestaurantModel", b =>
                {
                    b.Navigation("TablesModel");
                });

            modelBuilder.Entity("CourseGuide.Objects.Models.Entities.UserModel", b =>
                {
                    b.Navigation("RestaurantsModel");
                });
#pragma warning restore 612, 618
        }
    }
}
